#!/bin/sh

case $BUTTON in
    1) connman-gtk ;;
esac

if [[ $(connmanctl services) =~ ^\*.* ]]; then
    SIGNAL=2 dwmb_print "^c#9ece6a^ ^d^"
else
    SIGNAL=2 dwmb_print "^c#f7768e^󰀝 Disconnected^d^"
fi
