#!/bin/sh

case $BUTTON in
    1) impala ;;
esac

data=$(iwctl station wlan0 show)
state=$(echo "${data}" | grep State)
regex="^ *State *connected"
if [[ $state =~ $regex ]]; then
    SIGNAL=2 dwmb_print "^c#9ece6a^ ^d^"
else
    SIGNAL=2 dwmb_print "^c#f7768e^󰀝 Disconnected^d^"
fi
