#!/bin/sh

# NOTE: doas must not require a password for `tlp` and `tlp-stat`

current=$(doas tlp-stat -m)
selected=$(echo "Performance |Balanced |Power Saver" \
        | rofi -dmenu -sep '|' -i -select "Balanced" -p "Current: $current")

exec >&/dev/null
case $selected in
    "Performance ")
        doas tlp performance;;
    "Balanced ")
        doas tlp balanced;;
    "Power Saver")
        doas tlp power-saver;;
esac
