#!/bin/sh

# NOTE: sudo must not require a password for `tlp` and `tlp-stat`

current_profile=$(sudo tlp-stat -m)
selected_profile=$(echo "Performance |Balanced |Power Saver" | rofi -sep '|' -dmenu -i -p "$current_profile")

exec >&/dev/null
case $selected_profile in
    "Performance ")
        sudo tlp performance;;
    "Balanced ")
        sudo tlp balanced;;
    "Power Saver")
        sudo tlp power-saver;;
esac
