#!/bin/sh

# NOTE: sudo must not require a password for `tlp` and `tlp-stat`

current_profile=$(doas tlp-stat -m)
selected_profile=$(echo "Performance |Balanced |Power Saver" | rofi -sep '|' -dmenu -i -p "$current_profile")

exec >&/dev/null
case $selected_profile in
    "Performance ")
        doas tlp performance;;
    "Balanced ")
        doas tlp balanced;;
    "Power Saver")
        doas tlp power-saver;;
esac
