#!/bin/sh

case $BUTTON in
    1) alacritty -e btop & ;;
esac

# https://askubuntu.com/a/297978
output=$(vmstat 1 2 | tail -1 | awk '{
    usage = 100 - $15

    if (usage > 90)
        printf "^c#f7768e^"
    else if (usage > 75)
        printf "^c#e0af68^"

    print " " usage "%^d^"
}')

SIGNAL=4 dwmb_print $output
