#!/bin/sh

case $BUTTON in
    1) alacritty -e btop & ;;
esac

# https://stackoverflow.com/a/70760502
output=$(printf "%b" "import psutil\nprint('{}'.format(psutil.cpu_percent(interval=1)))" | python3 | awk '{
    usage = int($0)

    if (usage > 90)
        printf "^c#f7768e^"
    else if (usage > 75)
        printf "^c#e0af68^"

    print " " usage "%^d^"
}')

SIGNAL=4 dwmb_print $output
