#!/bin/sh

case $BUTTON in
    1) wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle & ;;
    3) alacritty -e wiremix & ;;
esac

# Inspired By: Jake@Linux https://gitlab.com/jped/scripts/-/blob/main/volume?ref_type=heads

color=""
[ $(pamixer --get-mute) = true ] && color="^c#595d70^"

SIGNAL=1 dwmb_print " ${color}󰓃 $(pamixer --get-volume)%^d^"
