#!/bin/sh

free -h --si | awk '/^Mem/{
    # check only if in Gb
	if (index($3, "G") != 0) {
        # conv to int
		used = $3+0
		avail = $2+0
		if (used > (0.75 * avail)) {
			printf "^c#e0af68^"
		} else if (used > (0.85 * avail)) {
			printf "^c#f7768e^"
		}
	}
	print " " $3 "/" $2 "^d^"
}'
