#!/bin/sh

free | awk '/^Mem/{
    used = int($3)
    avail = int($2)
    usage = int((used/avail)*100)

    # check only if in Gb
	if (index($3, "G") != 0) {
		if (usage > 75)
			printf "^c#e0af68^"
		else if (usage > 85)
			printf "^c#f7768e^"
	}
	print " " usage "%"
}'
